## counts_visits table definition
---
name: counts_visits
primarykey: id
engine: InnoDB
charset: utf8
autoincrement:
    colname: id
    start: 1
cols:
    id:
        type: bigint
        length: 20
        params: NOT NULL
    year:
        type: bigint
        length: 20
        params: NOT NULL
    month:
        type: bigint
        length: 20
        params: NOT NULL
    day:
        type: bigint
        length: 20
        params: NOT NULL
    countunique:
        type: bigint
        length: 20
        params: NOT NULL
    counthits:
        type: bigint
        length: 20
        params: NOT NULL
indices:
    year_day:
        col:
            year
            month
            day
        isUnqiue: true
    year:
        col: year
        isUnqiue: false
    month:
        col: month
        isUnqiue: false
defaultvalues:
    rows:
