## tab1 table definition
---
name: messages
primarykey: id
engine: InnoDB
charset: utf8
autoincrement:
    colname: id
    start: 1
cols:
    id:
        type: bigint
        length: 20
        params: NOT NULL
    text:
        type: text
        length: 
        params: NOT NULL
    starttime:
        type: bigint
        length: 20
        params: NOT NULL
    stoptime:
        type: bigint
        length: 20
        params: NOT NULL
    nocomments:
        type: bool
        length: 
        params: 
indices:
defaultvalues:
    rows:
