## Module controller map
---
descriptions:
    top:
        headline: GLOBAL_INFO
        text: >
            Um die Anzeige anzupassen, erstelle im FanPress CM-Unterordner
            <em>/data/nkorg_polls/templates</em> eine Kopie der jeweiligen
            Datei mit der Endung <em>.custom.html</em>.
            <dl>
                <dt>voteform_header.html</dt>
                <dd class="mb-1">Kopfzeile einer Umfrage im Votingformular</dd>
                <dt>voteform_line.html</dt>
                <dd class="mb-1">Zeile einer Antwort im Votingformular</dd>
                <dt>voteform_footer.html</dt>
                <dd class="mb-1">Fußzeile im Votingformular</dd>
                <dt>result_header.html</dt>
                <dd class="mb-1">Kopfzeile einer Umfrage im Ergebnisformular</dd>
                <dt>result_line.html</dt>
                <dd class="mb-1">Zeile einer Antwort im Ergebnisformular</dd>
                <dt>result_footer.html</dt>
                <dd class="mb-1">Fußzeile im Ergebnisformular</dd>
                <dt>archive_footer.html</dt>
                <dd class="mb-1">Fußzeile im Archiv</dd>
            </dl>
show_latest_poll:
    type: boolSelect
    conf:
        text: GUI_CONFIG_SHOWLATEST
        data:
            remove_corner_left: 1
        icon: sort-alpha-down-alt
        size: lg
        class: >
            col-12 col-sm-6 col-md-1 fpcm-ui-field-input-nowrapper-general pr-0
        labelClass: >
            col-12 col-sm-6 col-md-3 fpcm-ui-field-label-general
chart_type:
    type: boolSelect
    conf:
        options: $charTypes
        text: GUI_CONFIG_CHARTTYPE
        data:
            remove_corner_left: 1
        icon: chart-pie
        size: lg
        class: >
            col-12 col-sm-6 col-md-1 fpcm-ui-field-input-nowrapper-general pr-0
        labelClass: >
            col-12 col-sm-6 col-md-3 fpcm-ui-field-label-general
vote_expiration_default:
    type: textInput
    conf:
        text: GUI_POLL_COOKIE_DEFAULT
        wrapper: false
        type: number
        icon: stopwatch
        size: lg
        class: >
            col-12 col-sm-6 col-md-1 fpcm-ui-field-input-nowrapper-general pr-0
        labelClass: >
            col-12 col-sm-6 col-md-3 fpcm-ui-field-label-general